#!/bin/bash

if [ ! -f app/console ] ; then
    echo -e '\033[41;37;1m'
    printf "Unable to find $PWD/app/console\n"
    printf "$PWD is it your project root directory ?"
    echo -e '\033[m'
    exit 
fi

if [ $# = 0 ] ; then
    php app/console
    exit
fi

cmd="php"

if [ $1 != "app/console"  ] ; then
    cmd+=" app/console"
fi


for var in "$@"
do
    cmd+=" $var"
done

# execute  php app/console ...
$cmd

# Extra command. Eg modify 'cache' and 'logs' permission
#chown -R apache:apache app/cache
#chown -R apache:apache app/logs
